/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_githib_bedrin_wininet4j_WinInet4J */

#ifndef _Included_com_githib_bedrin_wininet4j_WinInet4J
#define _Included_com_githib_bedrin_wininet4j_WinInet4J
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_githib_bedrin_wininet4j_WinInet4J
 * Method:    getProxyHost
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_githib_bedrin_wininet4j_WinInet4J_getProxyHost
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
